std_msgs/Header header                               # Header timestamp should be acquisition time of image detection published                       
string trafficlight_id                               # Id of the detected trafficlight
sensor_msgs/RegionOfInterest trafficlight_roi        # Bounding box information of detected traffic light
string color                                       # Color information of detected traffic light   

